### ISSUE TITLE
Section A - Questions

### ISSUE THREAD

**Issue by doubleedesign** [studentPaulStuart/Tafe21S204#7]
1. List and describe briefly for three Agile methodologies are commonly used in the Software development industry.
2. State which methodology you will use for the Start_Finance project and justify why you choose this methodology.
3. List and briefly describe three Project Management Software for software development projects.
4. State which project management software you will use for the Start_Finance project and justify why you choose this software to use.
5. List and briefly describe three different source control software which are commonly used in the software development industry.
6. State which source-control system you will use for the Start_Finance project and justify why you choose this system to use.
7. List and describe three collaboration software which are commonly used in the Software development industry.
8. State which collaboration software you will use for the Start_Finance project and justify why you choose this system to use.

**Comment by studentPaulStuart** [comment]
@doubleedesign @Bastiann24 I'll take questions 3,6,8 and answer here

**Comment by studentPaulStuart** [comment]
Hi Guys here are questions 1-8 completed;

1.	List and describe briefly for three Agile methodologies are commonly used in the Software development industry.

Scrum is one of the most used of the many frameworks of the Agile methodology. Scrum is characterized by cycles or stages of development, known as sprints, and by the maximization of development time for a software product. It is good in that it utilizes many team members and maximizes the power of teamwork but has the disadvantage of loosing track of the big picture and not having clearly defined roles.

Kanban is of Japanese origin and its meaning is linked to a time concept, “just-in-time”. In practice, the Kanban method exists in a board or table (Kanban board), divided into columns, that shows every flow of the software production. As the development evolves, the information contained in the table changes, and when a new task comes into play, a new “card” is created. The Kanban method requires communication and transparency so that the members of a team can know exactly at what stage the development is and can see the status of the project at any time.

The Lean method offers a conceptual framework and follows values, principles and good development practices that can be applied to an Agile development approach. Developed for Toyota manufacturing it has been applied to software development. It has seven principles to follow; Deleting the things that do not matter, Quality Development, creating knowledge, differing commitments, fast delivery, respecting the team, optimize the whole.

2.	State which methodology you will use for the Start Finance project and justify why you choose this methodology.
We will use the Kanban method as the team members are not always working present and in physical contact. Often people are picking up tasks at different times, so it makes sense we have a noticeboard, or work board style approach. Scrum would be excellent however team members are all working remotely.
3.	List and briefly describe three Project Management Software for software development projects.
MS Project is Microsoft’s desktop application that is used for highly detailed projects with many moving parts, budgets, and staff to manage. It allows different views of the workflow, allows staff management to ensure people aren’t over allocated and that tasks are completed before new ones start. It can be used for software and other non-software projects.
Trello. This is an online web application that has free and paid for features. It utilizes the Kanban board approach however is not exclusively set up for that only. It has many customizable features and extra elements that can be add on.
Teamwork – This PM software is also web based and is ideal for small teams. It can send bills and invoices as well. It also has an android and IOS application for sending notifications etc. It gives a simple layout but still allows a project to managed without over-allocating tasks to staff. Shows visuals and Gantt charts so people can see work progress.

4.	State which project management software you will use for the Start Finance project and justify why you choose this software to use.

We will use the GitHub discussion, issues and board that comes with the platform, that way it integrates with our tasks and uploads.

5.	List and briefly describe three different source control software which are commonly used in the software development industry.
Git – One of the best version control tools that provides strong support for non-linear development (Agile). It allows key encryption and is fast and easy to use. It can become difficult to understand the log history as a project gets bigger or more complex.
VSTS – Visual Studio team service is Microsoft’s own version control system for client-server repository interactions. Supportive of almost any programming language. Not very good for large teams however is good for small projects.
Clear Case by IBM – is a client-server repository model based on software configuration management tool. Is very good for large scale enterprise projects and large files, binaries, and sizes. It allows branching, labelling, and versioning of directories.
6.	State which source-control system you will use for the Start Finance project and justify why you choose this system to use.
Tortoise Git will be the version control software we use as we have the most familiarity to it. We understand how to view the source map and see changes that have been made to the project. Our team also know how to make changes and ensure it is version controlled so others can see what has been developed.
7.	List and describe three collaboration software which are commonly used in the Software development industry.

Gitea - It runs anywhere can compile for Windows, macOS, Linux, etc. Easy to install as you need to run the binary for your platform. Or you can also ship Gitea with Vagrant or Docker
Cloud Source Repository – This is Googles software Dev Collaboration tool. Very similar to GitHub and in fact syncs with GitHub and gutbucket. It is also a lot more than that as it can run cloud software and other features, some are free, others are paid.
Beanstalk is a secure and most reliable GitHub alternative tool. It helps you to manage source code repositories. It is designed to improve your development workflow. It supports Git Version control and allows tools such as feedback, issues, and discussions.

8.	State which collaboration software you will use for the Start Finance project and justify why you choose this system to use.

GitHub will be used as it is what everyone has most training and practice with. It is also very good at working in conjunction with Tortoise Git version control because it can pick up on changes, branches and the development cycle is mapped. It is also easy to collaborate with the issues, discussion board and Kanban board that links up with the software version controlling and branch work being done by each collaborator.
